export const SET_COLUMN_ORDER = "SET_COLUMN_ORDER";
export const SET_NEW_SAME_COLUMN = "SET_NEW_SAME_COLUMN";
export const SET_NEW_COLUMN = "SET_NEW_COLUMN";
export const ADD_NEW_COLUMN = "ADD_NEW_COLUMN";
export const REMOVE_COLUMN = "REMOVE_COLUMN";
export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const SET_COLUMN_TITLE = "SET_COLUMN_TITLE";
export const SET_TASK_TITLE = "SET_TASK_TITLE";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADD_USER_TO_BOARD = "ADD_USER_TO_BOARD";
export const REMOVE_USER_FROM_BOARD = "REMOVE_USER_FROM_BOARD";

export const ADD_BOARD_TO_USER = "ADD_BOARD_TO_USER";
export const REMOVE_BOARD_FROM_USER = "REMOVE_BOARD_FROM_USER";

export const FETCH_INITIAL_STATE = "FETCH_INITIAL_STATE"; 
